### PR TITLE
ssm bash-completion v1

### PR DESCRIPTION
**Pull request by beneso**
This version was made for system-storage-manager-0.5-0.fc27. It treats all actions in that version. Keeps track of options used (those are not displayed) and offers suitable block devices for respective actions.

### CODE REVIEW

**Comment by jtulak** [comment]
Thanks for the PR, this is certainly something useful. Can you add the two new commands, `info [ITEM]` and `migrate FROM TO` that are in the latest version (not yet in Fedora stable)?

**Comment by beneso** [comment]
Thanks for your reply. I'll have a look at that.

**Comment by beneso** [comment]
With the latest commits, it should be ready. Tested on Fedora Rawhide, built 25th June, system-storage-manager-1.0-0.fc29.noarch.

EDIT: the bash-completion file moved into bash-completion/ssm

**Comment by jtulak** [comment]
Nice. :-) The only two issues I see with it: 
1) I can't get over `_init_completion`. if I comment it out, it works ok, but I can't find out in any manual what exactly this function should do and why both on my f27, f28 and centos7.6 it always ends with non-zero code. I guess this is an issue on my side, because this function is used in many scripts I found online, although none in `/etc/bash_completion.d/` on any of my systems uses it...
I mean, the function is in my bash, it just always ends with `return 1`. I'm using this completion script with `source ./ssm` if it is not in `/etc/bash_completions.d`

2) Not a pretty result when running without root:
```
$ sudo ssm create <TAB>
Root privileges required to run this script!


Root privileges required to run this script!
```
So I think it needs some `whoami` check that disables all the smart parts and does a fallback to the normal way of completion any file/directory instead of calling ssm and failing.

Other than that (and a few trailing whitespaces) it seems ok. I'm sending it to the mailing list as a single patch in case anyone out there wants to see it too. And I'm offline in the next week, sorry for any delayed replies in advance. :-)

**Comment by jtulak** [comment]
I fixed the issues, you can find it in the mailing list: https://sourceforge.net/p/storagemanager/mailman/message/36367194/

If I hear no feedback in a few weeks and find no more issues, I will merge the modified version.

**Comment by beneso** [comment]
Thank you for fix. I have no access to ssm now, and limited access to internet. Apoligies for not letting you know. The soonest I will be able to check that out is next week (starting 23rd of July).

**Comment by beneso** [comment]
Your fixes included. Thanks a lot for help! :)

**Comment by jtulak** [comment]
Thanks. It looks good, I have just last three things, hopefully small. 

First, there are trailing whitespaces. Git diff flashes all red when it finds them... :-) Second, can you squash this PR into a single commit? And the last: why are the paths hardcoded, like `readonly SSM="/usr/bin/ssm"`? Shouldn't we respect `$PATH`? (And that's completely ignoring aliases for now.) A grep over my `/etc/bash_completion.d/` did not find any script using `/usr/bin/` or `/bin/` path. I mean, maybe it is the right thing to do in this case, but I need to know why.

**Comment by jtulak** [comment]
I fixed the issues I mentioned above and sent the patch to SSM's mailing list. I will merge the patch after a two weeks review period.

https://sourceforge.net/p/storagemanager/mailman/storagemanager-devel/thread/20181121175345.65495-1-jtulak%40redhat.com/#msg36473731

**Pull request closed without merging**
